sudo: require
services:
    - docker

before_install:
    - docker build -t enguillem/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true enguillem/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-672742122306"
    bucket_path: "docker"
    on:
        branch: master
    acces_key_id: "$AWS_ACCESS_KEY"
    secret_acces_key:
        secure: "$AWS_SECRET_KEY"

        